### ISSUE TITLE
function selector was not recognized and there's no fallback function

### ISSUE THREAD

**Issue by r0wdy1** [zkBob/load_runner#5]
```
eth_sendRawTransaction
  Contract call:       ZeroPoolProxy#<unrecognized-selector>
  Transaction:         0x5f6a6df1265c70062441ed4221684d9300ba0065f5491e192be1b958121a3f9f
  From:                0x22d491bde2303f2f43325b2108d26f1eaba1e32b
  To:                  0xc89ce4735882c9f0f0fe26686c53074e09b0d550
  Value:               0 ETH
  Gas used:            42838 of 2000000
  Block #38:           0x1b36787a1258ed7429014edbeb2d19b5db95298c9df69ffec5e83836ce40ae7f

  Error: Transaction reverted: function selector was not recognized and there's no fallback function
      at Pool.<unrecognized-selector> (contracts/Pool.sol:17)
      at ZeroPoolProxy._delegate (@openzeppelin/contracts/proxy/Proxy.sol:30)
      at ZeroPoolProxy._fallback (@openzeppelin/contracts/proxy/Proxy.sol:59)
      at ZeroPoolProxy.<fallback> (@openzeppelin/contracts/proxy/Proxy.sol:67)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

Mined empty block range #39 to #41
eth_call
  Contract call:       ZeroPoolProxy#<unrecognized-selector>
  From:                0x90f8bf6a479f320ead074411a4b0e7944ea8c9c1
  To:                  0xc89ce4735882c9f0f0fe26686c53074e09b0d550

eth_call
  Contract call:       ZeroPoolProxy#<unrecognized-selector>
  From:                0x90f8bf6a479f320ead074411a4b0e7944ea8c9c1
  To:                  0xc89ce4735882c9f0f0fe26686c53074e09b0d550

eth_getTransactionCount
eth_gasPrice
eth_sendRawTransaction
  Contract call:       ZeroPoolProxy#<unrecognized-selector>
  Transaction:         0x809bebe932247b91e36b0a1097c36a492ebe8abc765a7cde7a967bd2a001c844
  From:                0x22d491bde2303f2f43325b2108d26f1eaba1e32b
  To:                  0xc89ce4735882c9f0f0fe26686c53074e09b0d550
  Value:               0 ETH
  Gas used:            171858 of 2000000
  Block #42:           0x4b7cb423d9402596634bf534cd9f63415cef6e87f8623cc534070342f879a597

  console.log:
    permittable token address: 0xd833215cbcc3f914bd1c9ece3ee7bf8b14f841bb
    allowance:  0
    deposit_spender: 0xffcf8fdee72ac11b5c542428b35eef5769c409f0,
  amount: 1000000000,
  current balance: 999998000000000,
  

  Error: VM Exception while processing transaction: reverted with reason string 'ERC20: transfer amount exceeds allowance'
      at Pool.verifyCallResult (@openzeppelin/contracts/utils/Address.sol:209)
      at Pool.functionCallWithValue (@openzeppelin/contracts/utils/Address.sol:132)
      at Pool.functionCall (@openzeppelin/contracts/utils/Address.sol:94)
      at Pool._callOptionalReturn (@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol:92)
      at Pool.safeTransferFrom (@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol:34)
      at Pool.transact (contracts/Pool.sol:125)
      at ZeroPoolProxy._delegate (@openzeppelin/contracts/proxy/Proxy.sol:30)
      at ZeroPoolProxy._fallback (@openzeppelin/contracts/proxy/Proxy.sol:59)
      at ZeroPoolProxy.<fallback> (@openzeppelin/contracts/proxy/Proxy.sol:67)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)


Mined empty block range #43 to #44
eth_getBlockByNumber
eth_gasPrice
eth_chainId
eth_getTransactionCount
eth_getBlockByNumber
eth_gasPrice
eth_sendRawTransaction
  Contract call:       PermittableToken#mint
  Transaction:         0x2115b78332710275455bc72c43bf7d79417e48e9d1c4cec694b1caf06ccbca54
  From:                0x90f8bf6a479f320ead074411a4b0e7944ea8c9c1
  To:                  0xd833215cbcc3f914bd1c9ece3ee7bf8b14f841bb
  Value:               0 ETH
  Gas used:            34328 of 100000
  Block #45:           0x9da1f16dd952377fd65c2ea0f74976ef86ea5a43ef6de0b0fbe0065141e700e7

eth_getTransactionReceipt
eth_call
  Contract call:       PermittableToken#balanceOf
  From:                0x90f8bf6a479f320ead074411a4b0e7944ea8c9c1
  To:                  0xd833215cbcc3f914bd1c9ece3ee7bf8b14f841bb

eth_call
  Contract call:       PermittableToken#allowance
  From:                0x90f8bf6a479f320ead074411a4b0e7944ea8c9c1
  To:                  0xd833215cbcc3f914bd1c9ece3ee7bf8b14f841bb

eth_getBlockByNumber
eth_gasPrice
eth_chainId
eth_getTransactionCount
eth_getBlockByNumber
eth_gasPrice
eth_sendRawTransaction
  Contract call:       PermittableToken#approve
  Transaction:         0xc4353545c36859e29655ea80e6b05f32590bbdc5b9990d34f9c413136c73f729
  From:                0xffcf8fdee72ac11b5c542428b35eef5769c409f0
  To:                  0xd833215cbcc3f914bd1c9ece3ee7bf8b14f841bb
  Value:               0 ETH
  Gas used:            46295 of 100000
  Block #46:           0x4bc9f5bd472aaf35de4ad1a933b243de6fbbb3f9b0a9664350265ebc50222ab8

eth_getTransactionReceipt
eth_call
  Contract call:       PermittableToken#allowance
  From:                0x90f8bf6a479f320ead074411a4b0e7944ea8c9c1
  To:                  0xd833215cbcc3f914bd1c9ece3ee7bf8b14f841bb

Mined empty block #47 with base fee 2002346
eth_call
  Contract call:       ZeroPoolProxy#<unrecognized-selector>
  From:                0x90f8bf6a479f320ead074411a4b0e7944ea8c9c1
  To:                  0xc89ce4735882c9f0f0fe26686c53074e09b0d550

eth_call
  Contract call:       ZeroPoolProxy#<unrecognized-selector>
  From:                0x90f8bf6a479f320ead074411a4b0e7944ea8c9c1
  To:                  0xc89ce4735882c9f0f0fe26686c53074e09b0d550

eth_getTransactionCount
eth_gasPrice
eth_sendRawTransaction
  Contract call:       ZeroPoolProxy#<unrecognized-selector>
  Transaction:         0xacc28a8e2e0e61d189943b36263bbe64e4a523a77d5ec60d9ce603631c29c342
  From:                0x22d491bde2303f2f43325b2108d26f1eaba1e32b
  To:                  0xc89ce4735882c9f0f0fe26686c53074e09b0d550
  Value:               0 ETH
  Gas used:            177116 of 2000000
  Block #48:           0x074ba074ff0d911e02df6db8d5990b12bf2b939079b8d7bbbeef65c322f031bb

  console.log:
    permittable token address: 0xd833215cbcc3f914bd1c9ece3ee7bf8b14f841bb
    allowance:  100000000000
    deposit_spender: 0xffcf8fdee72ac11b5c542428b35eef5769c409f0,
  amount: 1000000000,
  current balance: 100000999998000000000,
  

eth_getTransactionReceipt
Mined empty block range #49 to #52
```

**Comment by r0wdy1** [comment]
[relayer.txt](https://github.com/zkBob/load_runner/files/8554880/relayer.txt)
